SELECT
3 AS FILIAL
, FUNCIONARIO.CODIGO AS CODIGO
, FUNCIONARIO.FANTASIA AS FANTASIA
, FUNCIONARIO.NOME AS NOME
, FUNCIONARIO.CPF AS CPF
, FUNCIONARIO.RG AS RG
, FUNCIONARIO.DATA AS DATA
, FUNCIONARIO.DATANASC AS DATANASC
, FUNCIONARIO.ENDERECO AS ENDERECO
, CIDADE.CODIGOFISCAL AS CODIGOFISCAL
, BAIRRO.NOME AS NOMEBAIRRO
, FUNCIONARIO.COMPLEMENTO AS COMPLEMENTO
, FUNCIONARIO.CEP AS CEP
, FUNCIONARIO.TELEFONE AS TELEFONE
, FUNCIONARIO.EMAIL AS EMAIL
FROM FUNCIONARIO
INNER JOIN CIDADE ON CIDADE.CODIGO = FUNCIONARIO.CIDADE
INNER JOIN BAIRRO ON BAIRRO.CODIGO = FUNCIONARIO.BAIRRO
WHERE FUNCIONARIO.CODIGO IN (SELECT FUNCIONARIO FROM FUNCIONARIOCLIFOR WHERE CLIFOR IN (SELECT CODIGO FROM CLIFOR WHERE FILIAL = 1))
AND FUNCIONARIO.CODIGO IN (SELECT FUNCIONARIO FROM ROTA WHERE FILIAL = 1)