CREATE TABLE CLIFORDEPARA (
    FILIAL INTEGER NOT NULL,
    DE INTEGER NOT NULL,
    PARA INTEGER NOT NULL);

ALTER TABLE CLIFORDEPARA
ADD CONSTRAINT PK_CLIFORDEPARA
PRIMARY KEY (FILIAL,DE,PARA);

ALTER TABLE CLIFORDEPARA
ADD CONSTRAINT FK_CLIFORDEPARA_1
FOREIGN KEY (FILIAL)
REFERENCES FILIAL(CODIGO);

ALTER TABLE CLIFORDEPARA
ADD CONSTRAINT FK_CLIFORDEPARA_2
FOREIGN KEY (PARA)
REFERENCES CLIFOR(CODIGO);

